import numpy as np
import matplotlib.pyplot as plt

RFpower = np.arange(-1, 10)
RealIFpower = np.array([-6.95,-6.37,-5.89,-5.56,-5.29,-5.08,-4.92,-4.76,-4.65,-4.56,-4.37])
conversion = RealIFpower - RFpower
IdealIFpower = RFpower + conversion[1]
p1dbindx = np.argmin(np.abs(IdealIFpower - RealIFpower - 1))
interpP1db = np.interp(x, RFpower, np.abs(IdealIFpower - RealIFpower - 1))
print(f'p1dbindx: {p1dbindx}. RealIFpower[p1dbindx] = {RealIFpower[p1dbindx]}. IdealIFpower[p1dbindx] = {IdealIFpower[p1dbindx]}')
plt.figure(1)
plt.plot(RFpower, conversion)
plt.grid()
plt.xlabel('RF power [dBm]')
plt.ylabel('Conversion [dBm]')
plt.title('Conversion Loss of the Didoe Ring Mixer versus RF Power')
plt.savefig('images/conversion.png')
plt.show()
fig2 = plt.figure(2)
ax = fig2.add_subplot(111)
ax.plot(RFpower,RealIFpower,label='Measured IF Power (dBm)')
ax.plot(RFpower,IdealIFpower,label='Ideal IF Power (dBm)')
ax.legend()
vec = np.linspace(-1,RFpower[p1dbindx], 10)
ax.plot(vec, np.ones(len(vec)) * RealIFpower[p1dbindx], 'r--')
ax.plot(vec, np.ones(len(vec)) * IdealIFpower[p1dbindx], 'r--')
ax.scatter(RFpower[p1dbindx], RealIFpower[p1dbindx], marker='x', color='b')
ax.scatter(RFpower[p1dbindx], IdealIFpower[p1dbindx], marker='x', color='b')
ax.set_xlim([-1,9])
ax.set_ylim([-7, 4])
ax.annotate(f'({np.round(RFpower[p1dbindx], 3)}, {np.round(RealIFpower[p1dbindx], 3)})', (RFpower[p1dbindx], RealIFpower[p1dbindx]))
ax.annotate(f'({np.round(RFpower[p1dbindx], 3)}, {np.round(IdealIFpower[p1dbindx], 3)})', (RFpower[p1dbindx], IdealIFpower[p1dbindx]))
ax.grid()
ax.set_xlabel('RF power [dBm]')
ax.set_ylabel('IF power [dBm]')
ax.set_title('1dBm compression point of the Diode Ring Mixer')
plt.savefig('images/p1db.png')
plt.show()
